### ISSUE TITLE
Включить в список настроек autosafe

### ISSUE THREAD

**Issue by maestroprog** [iassasin/phplate#11]
- [x] Добавить опцию `autosafe` в настройки.

- [x] По умолчанию `autosafe` должен быть включен, с возможностью выключить его для всего шаблонизатора.

- [x] Если `autosafe` включен, то для всех переменных, которые выводятся в шаблоне, должна применяться встроенная функция `safe`.

- [x] Если для обработки вывода переменных уже используется функция `safe`, она должна применяться к переменной единожды.

**Comment by iassasin** [comment]
#17 выполнено
