### ISSUE TITLE
Отдельная папка для кэша

### ISSUE THREAD

**Issue by iassasin** [iassasin/phplate#18]
Переделать кэширование на использование отдельной настраиваемой папки.
Вопросы:
- Придумать алгоритм кэширования одноименных файлов, лежащих в разных каталогах
- Алгоритм определения, какой именно кэш-файл загрузить для указанного исходного файла шаблона.

**Comment by maestroprog** [comment]
Алгоритм простой - md5 от пути к файлу шаблона в рамках проекта.
Есть еще две проблемы которые нужно записать и решить:
 * Обновление кэша по mtime, к примеру
 * Чистка директории от устаревшего кэша

**Comment by iassasin** [comment]
- По поводу обновления не понял: до реализации отдельной директории для кэша уже было обновление кэша по сравнению времени изменения файлов кэша и исходника.
- Чистка от устаревшего кэша нереализуема (нельзя из имени кэш-файла узнать путь к исходнику) и не нужна. Проще очистить весь кэш в случае его сильного засорения. Перегенерация не сильно и не надолго замедлит работу приложения.

**Comment by maestroprog** [comment]
> уже было обновление кэша

Точно, было, я подзабыл.

> очистить весь кэш

согласен, логично, я слишком преувеличил проблему в голове в момент написания отчёта.
