### ISSUE TITLE
Построение шаблонов из произвольных файлов

### ISSUE THREAD

**Issue by iassasin** [iassasin/phplate#19]
Добавить метод, например `buildFile($file, $args)`

**Comment by maestroprog** [comment]
Не совсем ясна суть задачи.

**Comment by iassasin** [comment]
Нужен аналог такому коду:
```php
Template::buildStr(file_get_contents('/path/to/file.random.ext'), $args);
```

**Comment by maestroprog** [comment]
~Т.е. шаблонизация без внутреннего кэша?~
Понял, чтобы можно было тянуть шаблоны из любого места.
А не выгоднее ли эту фунциональность в `Template::build()` реализовать?

**Comment by maestroprog** [comment]
> Template::buildStr(file_get_contents('/path/to/file.random.ext'), $args);

Кстати, ты только тут написал код, которому не нужен аналог, мне кажется :)

**Comment by iassasin** [comment]
Как раз таки, при использовании встроенной функции будет делаться кэш.
> А не выгоднее ли эту фунциональность в `Template::build()` реализовать?

Не получится: относительный путь от пути от корня папки шаблонов не отличить.

**Comment by maestroprog** [comment]
А, ну если делать кэш, тогда нужен отдельный метод.
