### ISSUE TITLE
Переопределение пайп-функций

### ISSUE THREAD

**Issue by maestroprog** [iassasin/phplate#25]
Планировали это сделать, сейчас при попытке переопределения кидается исключение.
Нужно продумать, как должно будет работать переопределение встроенных пайп-функций, и нужно ли вообще переопределение встроенных функций.

**Comment by iassasin** [comment]
Да, пусть будет переопределение встроенных. Почему нет?

**Comment by maestroprog** [comment]
Ну да, но по хорошему нужно иметь ещё возможность restore встроенных функций после переопределения. Может еще какие идеи есть...

**Comment by iassasin** [comment]
Там же контейнер для пайп функций для каждого экземпляра свой, значит не нужно их восстанавливать. Кому в голову придет переопределять функции так, чтоб их потом надо было восстанавливать?
